name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  # docker-image-push:
  #   runs-on: ubuntu-latest
  #   steps:

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ vars.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         platforms: linux/arm64
  #         push: true
  #         tags: ${{ vars.DOCKERHUB_USERNAME }}/sketch:${{ github.run_number }}
  update-k8s-manifest:
  needs: docker-image-push
  runs-on: ubuntu-latest
  steps:
    - name: Checkout config repository
      uses: actions/checkout@v4
      with:
        repository: edwin-abraham-thomas/k8s  # You'll need to set this variable to your config repo name
        # token: ${{ secrets.CONFIG_REPO_TOKEN }}  # You'll need a PAT with access to the config repo
        
    - name: Update deployment manifest
      run: |
        # Use sed to update the image tag in the app.yaml file
        sed -i 's|image: ${{ vars.DOCKERHUB_USERNAME }}/sketch:.*|image: ${{ vars.DOCKERHUB_USERNAME }}/sketch:${{ github.run_number }}|g' sketch/app.yaml
        
    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add sketch/app.yaml
        git commit -m "Update sketch deployment to image tag ${{ github.run_number }}"
        git push