name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  update-k8s-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout config repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/k8s  # You'll need to set this variable to your config repo name
          token: ${{ secrets.CONFIG_REPO_TOKEN }}  # You'll need a PAT with access to the config repo
          ref: main
          
      - name: Update deployment manifest
        run: |
          # Use sed to update the image tag in the app.yaml file
          sed -i 's|image: ${{ vars.DOCKERHUB_USERNAME }}/sketch:.*|image: ${{ vars.DOCKERHUB_USERNAME }}/sketch:${{ github.run_number }}|g' sketch/app.yaml
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git diff
          git add sketch/app.yaml
          git commit -m "Update sketch deployment to image tag ${{ github.run_number }}"
          git push